### ISSUE TITLE
Bidirectional RPC with a worker

### ISSUE THREAD

**Issue by meh** [rustifybe/web-rpc#3]
What's the intended way to do this? Clone the worker on the page side and use the global scope for both the server and client on the worker side?

Create a `MessageChannel` on the page side, use it to create the server and then pass the other port along to the worker to create the client?

**Comment by allsey87** [comment]
> What's the intended way to do this? Clone the worker on the page side and use the global scope for both the server and client on the worker side?

Almost, [`web_sys::Worker`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Worker.html) and [`web_sys::DedicatedWorkerGlobalScope`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.DedicatedWorkerGlobalScope.html) already form a bi-directional channel that you can use with `web_rpc`. You just need to make an interface from each and then create a client, server, or both on each end.

See https://github.com/allsey87/webapp-mandelbrot-actors for a minimal example of this.

**Comment by meh** [comment]
But how do I do that when `Interface::new` takes the port by value? Do I turn the `Worker` into a `Port` first and then clone the port to create two interfaces?

Wait I just answered myself as I was asking the question, the generated docs were a bit obtuse and I didn't notice there was a variant that would return a tuple on `build` when using `with_service` and `with_client` at the same time.

Thanks :panda_face:
